config/routes.rb
Rails.application.routes.draw do

  get 'top/main'
  get 'cart/show'
  root 'top#main'
  resources 'product'
  resources :cartitems, only: [:create, :destroy]
  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cartitems, dependent: :destroy
  
end

app/models/cartitem.rb
class Cartitem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :cartitem
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @cartitems = Cartitem.all
  
    @total_price = 0
    @cartitems.each do |cartitems|
      @total_price += cartitems.product.price * cartitems.qty
    end
  end
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
  def create
    cartitem = Cartitem.new(qty:params[:qty], product_id:params[:product_id], cart_id:params[:cart_id])
    cartitem.save
    redirect_to product_index_path
  end
  
  def destroy
    cartitem = Cartitem.find(params[:id])
    cartitem.destroy
    redirect_to cart_show_path
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @products = Product.all
    @cartitem = Cartitem.new
  end
  
  def new
    @product = Product.new
  end
  
  def create
    product = Product.new(name:params[:product][:name], price:params[:product][:price])
    product.save
    redirect_to product_index_path
  end
  
  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to product_index_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart/show.html.erb
<% @cartitems.each do |cartitem| %>
  <p>
    <%= cartitem.product.name %><br>
    <%= cartitem.product.price %>円<br>
    <%= cartitem.qty %>個　
    <%= link_to '削除', cartitem, method: :delete %><hr>
  </p>
  
<% end %>

<br>
合計金額：<%= @total_price %>円

<hr>
<%= link_to '戻る', product_index_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>L61</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product/index.html.erb
<h1>商品一覧</h1>
<hr>
<% @products.each do |p| %>
<li>
  <%= p.name %>:
  <%= p.price %>円+税
  :<%= link_to '削除', p, method: :delete %>
  <%= form_tag cartitems_path(product_id: p.id), method: :post do %>
    <%= number_field_tag :qty %>個<br>
    <%= submit_tag 'カートに入れる' %>
  <% end %>
  <hr>
</li>
<% end %>

<%= link_to 'カートを表示する' , cart_show_path %><br>
<%= link_to '新商品追加', new_product_path %>

app/views/product/new.html.erb
<%= form_for @product, url:{action: :create} do |p| %>
  商品名:<%= p.text_field :name %>
  価格:<%= p.number_field :price %>円
  <%= p.submit '登録' %>
<% end %>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>

<h1><%= link_to 'ショッピングしよう', product_index_path %></h1>